<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>petStore</groupId>
  <artifactId>com.petStore</artifactId>
  <version>0.0.1-SNAPSHOT</version>
    <build>
	<pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.15.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.5</version>
          <configuration>
            <includes>
				<include>**/TestRunner.java</include>
			</includes>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>	
  </build>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.1</version>
      <scope>test</scope>
    </dependency>
    
	<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-core -->
	<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-core</artifactId>
    <version>7.11.2</version>
    <scope>compile</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-java -->
	<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>7.11.2</version>
    <scope>compile</scope>
	</dependency>
  
  	<!-- Source: https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting -->
	<dependency>
    <groupId>net.masterthought</groupId>
    <artifactId>cucumber-reporting</artifactId>
    <version>5.11.0</version>
    <scope>compile</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/io.rest-assured/json-schema-validator -->
	<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>json-schema-validator</artifactId>
    <version>6.0.0</version>
    <scope>compile</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/io.rest-assured/xml-path -->
	<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>xml-path</artifactId>
    <version>6.0.0</version>
    <scope>compile</scope>
	</dependency>

  <!-- Source: https://mvnrepository.com/artifact/org.hamcrest/hamcrest -->
	<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest</artifactId>
    <version>3.0</version>
    <scope>test</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
	<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.12.0</version>
    <scope>test</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
	<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>6.0.0</version>
    <scope>test</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-junit -->
	<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>7.11.2</version>
    <scope>test</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-gherkin -->
	<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-gherkin</artifactId>
    <version>7.11.2</version>
    <scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker -->
	<dependency>
    <groupId>com.github.javafaker</groupId>
    <artifactId>javafaker</artifactId>
    <version>1.0.2</version>
    <scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-testng -->
	<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>7.11.2</version>
    <scope>compile</scope>
	</dependency>

<!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind -->
	<dependency>
    <groupId>tools.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>3.1.3</version>
    <scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.json/json -->	
	<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20260522</version>
			<scope>compile</scope>
	</dependency>
	
	<!-- Source: https://mvnrepository.com/artifact/net.datafaker/datafaker -->
<dependency>
    <groupId>net.datafaker</groupId>
    <artifactId>datafaker</artifactId>
    <version>2.5.4</version>
    <scope>compile</scope>
</dependency>

</dependencies>
</project>